import { ArchitectureProject, NicheType } from '../types';
import { NICHE_FORM_CONFIGS } from './nicheFormConfigs';

export const getNicheSampleProjects = (niche: NicheType): ArchitectureProject[] => {
  const form = NICHE_FORM_CONFIGS[niche] || NICHE_FORM_CONFIGS.outro;

  switch (niche) {
    case 'vendas':
    case 'arte_decoracao':
      return [
        {
          id: `sample-${niche}-1`,
          title: 'Quadro Canvas Abstrato Ouro & Concreto (160x100cm)',
          clientName: 'Roberto M. Almeida',
          clientPhone: '(11) 98765-4321',
          clientEmail: 'roberto.almeida@gmail.com',
          category: 'quadros',
          location: 'São Paulo, SP (Envio Sedex)',
          state: 'SP',
          areaM2: 1.6,
          honorarios: 2850,
          paidAmount: 2850,
          status: 'entregue',
          coverImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=80',
          images: [
            'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=1200&q=80',
          ],
          description: 'Tela em canvas premium 100% algodão, chassi de madeira tratada e moldura canaleta em alumínio preto fosco. Envio protegido com seguro e nota fiscal.',
          startDate: '2026-08-01',
          deliveryDate: '2026-08-15',
          featured: true,
          tags: ['Canvas', 'Pronta Entrega', 'Abstrato', 'Moldura Canaleta'],
          createdAt: '2026-08-01',
        },
        {
          id: `sample-${niche}-2`,
          title: 'Díptico Botânico Fine Art com Vidro Antirreflexo',
          clientName: 'Carla Vasconcelos',
          clientPhone: '(21) 99123-4567',
          clientEmail: 'carla.vasc@hotmail.com',
          category: 'quadros',
          location: 'Rio de Janeiro, RJ (Retirada)',
          state: 'RJ',
          areaM2: 1.2,
          honorarios: 1980,
          paidAmount: 1980,
          status: 'aprovado',
          coverImage: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1200&q=80',
          images: [
            'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?auto=format&fit=crop&w=1200&q=80',
          ],
          description: 'Conjunto de dois quadros 60x80cm com impressão fine art sobre papel algodão Hahnemühle e paspatur neutro.',
          startDate: '2026-08-10',
          deliveryDate: '2026-08-28',
          featured: true,
          tags: ['Díptico', 'Fine Art', 'Botânico', 'Papel Algodão'],
          createdAt: '2026-08-10',
        },
        {
          id: `sample-${niche}-3`,
          title: 'Escultura Decorativa em Cerâmica Queimada & Madeira',
          clientName: 'Juliana Paes Decor',
          clientPhone: '(31) 98456-7890',
          clientEmail: 'juliana@interiores.com.br',
          category: 'decoracao',
          location: 'Belo Horizonte, MG (Transportadora)',
          state: 'MG',
          areaM2: 0.5,
          honorarios: 1450,
          paidAmount: 1000,
          status: 'em_producao',
          coverImage: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?auto=format&fit=crop&w=1200&q=80',
          images: [
            'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?auto=format&fit=crop&w=1200&q=80',
          ],
          description: 'Peça escultórica artesanal numerada para centro de mesa ou aparador.',
          startDate: '2026-08-15',
          deliveryDate: '2026-09-10',
          featured: false,
          tags: ['Escultura', 'Cerâmica', 'Design Autoral'],
          createdAt: '2026-08-15',
        },
      ];

    case 'consultoria':
      return [
        {
          id: `sample-consultoria-1`,
          title: 'Diagnóstico Operacional & Reestruturação de Vendas B2B',
          clientName: 'Grupo Vante Distribuidora',
          clientPhone: '(11) 98222-1100',
          clientEmail: 'diretoria@vante.com.br',
          category: 'estrategia',
          location: 'São Paulo, SP (Presencial e Remoto)',
          state: 'SP',
          areaM2: 60,
          honorarios: 18000,
          paidAmount: 12000,
          status: 'em_execucao',
          coverImage: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80',
          images: [
            'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=80',
          ],
          description: 'Mapeamento de funil comercial, capacitação de equipe de vendas externas e implementação de novos KPIs de faturamento.',
          startDate: '2026-07-01',
          deliveryDate: '2026-10-15',
          featured: true,
          tags: ['Consultoria B2B', 'Vendas', 'Processos', 'KPIs'],
          createdAt: '2026-07-01',
        },
        {
          id: `sample-consultoria-2`,
          title: 'Auditoria de Custos & Reorganização Financeira',
          clientName: 'InovaTech Serviços Ltda',
          clientPhone: '(21) 97111-2233',
          clientEmail: 'financeiro@inovatech.com',
          category: 'financeira',
          location: 'Rio de Janeiro, RJ (Remoto)',
          state: 'RJ',
          areaM2: 40,
          honorarios: 12500,
          paidAmount: 12500,
          status: 'entregue',
          coverImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80',
          images: [
            'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80',
          ],
          description: 'Redução de despesas operacionais em 18%, renegociação de fornecedores chave e implantação de DRE gerencial.',
          startDate: '2026-05-10',
          deliveryDate: '2026-07-20',
          featured: true,
          tags: ['Finanças', 'DRE', 'Redução de Custos'],
          createdAt: '2026-05-10',
        },
      ];

    case 'advocacia':
      return [
        {
          id: `sample-advocacia-1`,
          title: 'Assessoria Jurídica Mensal & Revisão de Contratos',
          clientName: 'Nexus Logística & Transportes',
          clientPhone: '(11) 99333-4455',
          clientEmail: 'contato@nexuslog.com.br',
          category: 'empresarial',
          location: 'São Paulo, SP (Tribunais e Remoto)',
          state: 'SP',
          areaM2: 12,
          honorarios: 9600,
          paidAmount: 9600,
          status: 'em_andamento',
          coverImage: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=1200&q=80',
          images: [
            'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=1200&q=80',
          ],
          description: 'Pareceres preventivos, adequação à LGPD, elaboração de contratos comerciais de alta complexidade e compliance.',
          startDate: '2026-06-01',
          deliveryDate: '2026-12-31',
          featured: true,
          tags: ['Contratos', 'Empresarial', 'LGPD', 'Assessoria'],
          createdAt: '2026-06-01',
        },
        {
          id: `sample-advocacia-2`,
          title: 'Planejamento Sucessório & Holding Familiar',
          clientName: 'Família Mendonça Dias',
          clientPhone: '(21) 98111-9988',
          clientEmail: 'mendonca.holding@gmail.com',
          category: 'civil',
          location: 'Rio de Janeiro, RJ',
          state: 'RJ',
          areaM2: 1,
          honorarios: 22000,
          paidAmount: 15000,
          status: 'elaboracao',
          coverImage: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=1200&q=80',
          images: [
            'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=1200&q=80',
          ],
          description: 'Estruturação de holding patrimonial, proteção de ativos, doação com reserva de usufruto e governança de sucessão.',
          startDate: '2026-07-15',
          deliveryDate: '2026-10-30',
          featured: true,
          tags: ['Holding Familiar', 'Sucessão', 'Tributário'],
          createdAt: '2026-07-15',
        },
      ];

    case 'design':
      return [
        {
          id: `sample-design-1`,
          title: 'Identidade Visual Completa & Manual de Marca (Brandbook)',
          clientName: 'Café Origem Torrefação Artesanal',
          clientPhone: '(31) 99888-7766',
          clientEmail: 'contato@cafeorigem.com.br',
          category: 'branding',
          location: 'Belo Horizonte, MG (Remoto)',
          state: 'MG',
          areaM2: 1,
          honorarios: 6800,
          paidAmount: 6800,
          status: 'aprovado',
          coverImage: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=1200&q=80',
          images: [
            'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=1200&q=80',
            'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=1200&q=80',
          ],
          description: 'Logotipo, paleta cromática, tipografia personalizada, embalagens para café especial e guia completo de aplicação.',
          startDate: '2026-07-01',
          deliveryDate: '2026-08-20',
          featured: true,
          tags: ['Branding', 'Embalagens', 'Café Especial', 'Brandbook'],
          createdAt: '2026-07-01',
        },
        {
          id: `sample-design-2`,
          title: 'Design de Aplicativo Mobile (UI/UX no Figma)',
          clientName: 'HealthFlow Telemedicina',
          clientPhone: '(11) 97654-3210',
          clientEmail: 'produto@healthflow.app',
          category: 'ui_ux',
          location: 'São Paulo, SP (Remoto)',
          state: 'SP',
          areaM2: 24,
          honorarios: 9500,
          paidAmount: 5000,
          status: 'em_criacao',
          coverImage: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80',
          images: [
            'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80',
          ],
          description: 'Pesquisa de usuários, wireframes de baixa e alta fidelidade, protótipo interativo no Figma e design system escalável.',
          startDate: '2026-08-01',
          deliveryDate: '2026-09-30',
          featured: true,
          tags: ['UI/UX', 'Figma', 'Mobile App', 'Design System'],
          createdAt: '2026-08-01',
        },
      ];

    case 'educacao':
      return [
        {
          id: `sample-educacao-1`,
          title: 'Mentoria Executiva VIP em Liderança e Negociação',
          clientName: 'Mariana Silveira (Diretora)',
          clientPhone: '(11) 98999-1234',
          clientEmail: 'mariana.exec@gmail.com',
          category: 'mentoria',
          location: 'Online (Zoom / 10 Encontros)',
          state: 'SP',
          areaM2: 20,
          honorarios: 7500,
          paidAmount: 7500,
          status: 'concluido',
          coverImage: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=1200&q=80',
          images: [
            'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=1200&q=80',
          ],
          description: 'Programa individualizado de 10 semanas para desenvolvimento de competências de liderança estratégica e resolução de conflitos.',
          startDate: '2026-06-01',
          deliveryDate: '2026-08-10',
          featured: true,
          tags: ['Mentoria VIP', 'Liderança', 'Online', 'Certificado'],
          createdAt: '2026-06-01',
        },
        {
          id: `sample-educacao-2`,
          title: 'Treinamento Corporativo de Comunicação & Vendas',
          clientName: 'Aliança Seguros S/A',
          clientPhone: '(21) 99876-5432',
          clientEmail: 'rh@aliancaseguros.com.br',
          category: 'corporativo',
          location: 'Rio de Janeiro, RJ (In-Company)',
          state: 'RJ',
          areaM2: 40,
          honorarios: 14000,
          paidAmount: 7000,
          status: 'em_andamento',
          coverImage: 'https://images.unsplash.com/photo-1531497865144-0464ef8fb9a9?auto=format&fit=crop&w=1200&q=80',
          images: [
            'https://images.unsplash.com/photo-1531497865144-0464ef8fb9a9?auto=format&fit=crop&w=1200&q=80',
          ],
          description: 'Workshop presencial para 35 corretores e gestores comerciais com apostilas, dinâmicas e avaliação de desempenho.',
          startDate: '2026-08-01',
          deliveryDate: '2026-09-15',
          featured: true,
          tags: ['Corporativo', 'In-Company', 'Vendas', 'Workshop'],
          createdAt: '2026-08-01',
        },
      ];

    case 'fotografia':
      return [
        {
          id: `sample-fotografia-1`,
          title: 'Ensaio Corporativo Executivo & Retratos de Marca',
          clientName: 'Camila Ferreira Advocacia',
          clientPhone: '(11) 98111-2244',
          clientEmail: 'camila@ferreiraadv.com',
          category: 'corporativo',
          location: 'São Paulo, SP (Estúdio & Escritório)',
          state: 'SP',
          areaM2: 50,
          honorarios: 3200,
          paidAmount: 3200,
          status: 'entregue',
          coverImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=80',
          images: [
            'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=80',
          ],
          description: 'Sessão fotográfica para sócios e associados, fotos para site, LinkedIn e materiais de imprensa com tratamento de pele profissional.',
          startDate: '2026-07-10',
          deliveryDate: '2026-07-25',
          featured: true,
          tags: ['Corporativo', 'Retratos', 'LinkedIn', 'Alta Resolução'],
          createdAt: '2026-07-10',
        },
        {
          id: `sample-fotografia-2`,
          title: 'Cobertura Fotográfica de Casamento & Making Of',
          clientName: 'Beatriz & Leonardo',
          clientPhone: '(21) 99444-5566',
          clientEmail: 'beatriz.casamento@gmail.com',
          category: 'casamento',
          location: 'Petrópolis, RJ (Quinta da Paz)',
          state: 'RJ',
          areaM2: 800,
          honorarios: 8900,
          paidAmount: 5000,
          status: 'em_edicao',
          coverImage: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80',
          images: [
            'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80',
          ],
          description: 'Cobertura de 10 horas de evento com dois fotógrafos, making of dos noivos, cerimônia, festa e álbum encadernado em linho.',
          startDate: '2026-08-05',
          deliveryDate: '2026-09-20',
          featured: true,
          tags: ['Casamento', 'Cerimônia', 'Álbum Linho', 'Making Of'],
          createdAt: '2026-08-05',
        },
      ];

    case 'saude_estetica':
      return [
        {
          id: `sample-saude-1`,
          title: 'Protocolo Integrado de Harmonização Facial & Rejuvenescimento',
          clientName: 'Fernanda Martins',
          clientPhone: '(11) 97222-3344',
          clientEmail: 'fernanda.martins@uol.com.br',
          category: 'estetica',
          location: 'Clínica Jardins - São Paulo, SP',
          state: 'SP',
          areaM2: 5,
          honorarios: 6800,
          paidAmount: 6800,
          status: 'concluido',
          coverImage: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80',
          images: [
            'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80',
          ],
          description: 'Planejamento facial digital 3D, preenchimento com ácido hialurônico, bioestimulador de colágeno e acompanhamento pós-procedimento.',
          startDate: '2026-07-15',
          deliveryDate: '2026-08-15',
          featured: true,
          tags: ['Harmonização', 'Bioestimulador', 'Estética Avançada'],
          createdAt: '2026-07-15',
        },
      ];

    case 'tecnologia':
      return [
        {
          id: `sample-tecnologia-1`,
          title: 'Desenvolvimento de Plataforma SaaS Cloud & APIs REST',
          clientName: 'FastPay Soluções Financeiras',
          clientPhone: '(11) 98888-0011',
          clientEmail: 'tech@fastpay.com.br',
          category: 'software',
          location: 'Remoto (Deploy AWS Cloud)',
          state: 'SP',
          areaM2: 120,
          honorarios: 24000,
          paidAmount: 16000,
          status: 'em_desenvolvimento',
          coverImage: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80',
          images: [
            'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80',
          ],
          description: 'Arquitetura de microsserviços Node.js + React/TypeScript, autenticação segura, gateway de pagamentos e pipeline CI/CD automatizado.',
          startDate: '2026-07-01',
          deliveryDate: '2026-10-30',
          featured: true,
          tags: ['SaaS', 'Cloud AWS', 'TypeScript', 'APIs'],
          createdAt: '2026-07-01',
        },
      ];

    default:
      // Default to general service / products
      return [
        {
          id: `sample-${niche}-1`,
          title: `Atendimento Especializado em ${form.itemLabel}`,
          clientName: 'Cliente Corporativo & Pessoal',
          clientPhone: '(11) 98888-1234',
          clientEmail: 'cliente@empresa.com.br',
          category: 'geral',
          location: 'Atendimento Nacional',
          state: 'SP',
          areaM2: 10,
          honorarios: 5500,
          paidAmount: 3500,
          status: 'em_andamento',
          coverImage: form.presetPhotos[0]?.url || 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
          images: form.presetPhotos.map((p) => p.url),
          description: `Serviço completo de ${form.itemLabel.toLowerCase()} com especificações acordadas, garantia de entrega e alto padrão de satisfação.`,
          startDate: '2026-08-01',
          deliveryDate: '2026-09-30',
          featured: true,
          tags: [form.itemLabel, 'Atendimento VIP', 'Profissional'],
          createdAt: '2026-08-01',
        },
      ];
  }
};
