import { NicheType } from '../types';

export interface NicheFormPresetPhoto {
  name: string;
  url: string;
}

export interface NicheFormConfig {
  modalTitleNew: string;
  modalTitleEdit: string;
  modalSubtitle: string;
  submitButtonText: string;
  itemLabel: string;
  itemLabelPlural: string;
  titleFieldLabel: string;
  titlePlaceholder: string;
  clientFieldLabel: string;
  clientPlaceholder: string;
  locationPlaceholder: string;
  metricFieldLabel: string;
  metricPlaceholder: string;
  showMetricField: boolean;
  valueFieldLabel: string;
  valuePlaceholder: string;
  photosSectionTitle: string;
  presetPhotosLabel: string;
  presetPhotos: NicheFormPresetPhoto[];
  showBeforeAfter?: boolean;
  beforeAfterTitle: string;
  beforeLabel: string;
  afterLabel: string;
  conceptFieldLabel: string;
  conceptPlaceholder: string;
  tagsFieldLabel: string;
  tagsPlaceholder: string;
  defaultTags: string[];
  emptyStateTitle: string;
  emptyStateDescription: string;
  emptyStateButtonText: string;
}

export const NICHE_FORM_CONFIGS: Record<NicheType, NicheFormConfig> = {
  educacao: {
    modalTitleNew: 'Nova Turma / Mentoria / Curso',
    modalTitleEdit: 'Editar Turma ou Mentoria',
    modalSubtitle: 'Cadastre turmas, programas de mentoria, alunos matriculados e acompanhe honorários e aulas.',
    submitButtonText: 'Publicar Turma / Conteúdo',
    itemLabel: 'Turma / Mentoria',
    itemLabelPlural: 'Turmas & Mentorias',
    titleFieldLabel: 'Nome da Turma, Curso ou Mentoria *',
    titlePlaceholder: 'Ex: Mentoria VIP de Liderança / Curso de Gestão',
    clientFieldLabel: 'Aluno(a) Principal ou Empresa Contratante *',
    clientPlaceholder: 'Ex: Mariana Silveira ou TechCorp Treinamentos',
    locationPlaceholder: 'Ex: Online (Zoom/Meet) ou Rio Bonito, RJ',
    metricFieldLabel: 'Carga Horária / Vagas',
    metricPlaceholder: 'Ex: 40h ou 15 vagas',
    showMetricField: true,
    valueFieldLabel: 'Valor da Matrícula / Investimento (R$)',
    valuePlaceholder: 'Ex: 2500',
    photosSectionTitle: 'Fotos da Turma, Apostilas & Sala de Aula',
    presetPhotosLabel: '💡 Imagens modelo de educação para inspiração rápida:',
    presetPhotos: [
      {
        name: 'Workshop & Sala de Aula',
        url: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Mentoria & Reunião Estratégica',
        url: 'https://images.unsplash.com/photo-1531497865144-0464ef8fb9a9?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Material Didático & Apostilas',
        url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Apresentação & Palestra',
        url: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=1200&q=80',
      },
    ],
    showBeforeAfter: true,
    beforeAfterTitle: '✨ Transformação & Resultados do Aluno (Antes & Depois)',
    beforeLabel: 'Diagnóstico Inicial / Antes da Mentoria',
    afterLabel: 'Conclusão / Certificado / Resultado Conquistado',
    conceptFieldLabel: 'Ementa, Metodologia & Detalhes do Conteúdo',
    conceptPlaceholder: 'Descreva os módulos, cronograma das aulas, ferramentas ensinadas, materiais didáticos e entregáveis aos alunos...',
    tagsFieldLabel: 'Competências & Formatos',
    tagsPlaceholder: 'Ex: Mentoria, Ao Vivo, Online, Gestão, Certificado',
    defaultTags: ['Mentoria', 'Online', 'Certificado'],
    emptyStateTitle: 'Seu espaço está limpo e pronto para cadastrar turmas!',
    emptyStateDescription: 'Cadastre sua primeira turma ou mentoria, defina vagas, valores e acompanhe matrículas.',
    emptyStateButtonText: '+ Cadastrar Nova Turma / Mentoria',
  },

  vendas: {
    modalTitleNew: 'Novo Produto ou Pedido de Venda',
    modalTitleEdit: 'Editar Produto ou Pedido',
    modalSubtitle: 'Cadastre itens do catálogo, pedidos comerciais, especificações e acompanhe as entregas e faturamento.',
    submitButtonText: 'Cadastrar Pedido / Produto',
    itemLabel: 'Produto / Venda',
    itemLabelPlural: 'Produtos & Vendas',
    titleFieldLabel: 'Nome do Produto, Pedido ou Lote *',
    titlePlaceholder: 'Ex: Pedido Atacado - Linha Premium 50 Peças',
    clientFieldLabel: 'Comprador / Empresa Parceira *',
    clientPlaceholder: 'Ex: Distribuidora Silva & Filhos LTDA',
    locationPlaceholder: 'Ex: Rio Bonito, RJ ou Cidade do Cliente',
    metricFieldLabel: 'Quantidade / Unidades',
    metricPlaceholder: 'Ex: 50 un ou 10 fardos',
    showMetricField: true,
    valueFieldLabel: 'Valor Total da Venda (R$)',
    valuePlaceholder: 'Ex: 8500',
    photosSectionTitle: 'Fotos do Produto & Catálogo Comercial',
    presetPhotosLabel: '💡 Imagens modelo de produtos e expedição:',
    presetPhotos: [
      {
        name: 'Showroom de Produtos',
        url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Embalagem & Logística',
        url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Catálogo Comercial',
        url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Transporte & Entrega',
        url: 'https://images.unsplash.com/photo-1616401784845-180882ba9ba8?auto=format&fit=crop&w=1200&q=80',
      },
    ],
    showBeforeAfter: true,
    beforeAfterTitle: '✨ Comparativo de Metas / Evolução de Vendas',
    beforeLabel: 'Status Inicial / Pedido Aberto',
    afterLabel: 'Entrega Realizada / Meta Atingida',
    conceptFieldLabel: 'Especificações Comerciais & Observações',
    conceptPlaceholder: 'Descreva condições de fornecimento, prazos de envio, tabela de descontos e garantias comerciais...',
    tagsFieldLabel: 'Tags & Linha de Produtos',
    tagsPlaceholder: 'Ex: Atacado, B2B, Pronta Entrega, Linha Premium',
    defaultTags: ['Atacado', 'Pronta Entrega'],
    emptyStateTitle: 'Seu catálogo comercial está limpo e pronto!',
    emptyStateDescription: 'Cadastre seu primeiro produto ou pedido de venda, envie fotos e gerencie suas comissões.',
    emptyStateButtonText: '+ Cadastrar Novo Produto / Venda',
  },

  advocacia: {
    modalTitleNew: 'Novo Processo ou Caso Jurídico',
    modalTitleEdit: 'Editar Caso Jurídico',
    modalSubtitle: 'Cadastre processos judiciais, pareceres consultivos, minutas contratuais e controle honorários advocatícios.',
    submitButtonText: 'Cadastrar Caso Jurídico',
    itemLabel: 'Caso / Processo',
    itemLabelPlural: 'Processos & Casos',
    titleFieldLabel: 'Título do Processo, Ação ou Parecer *',
    titlePlaceholder: 'Ex: Ação Revisional Cível / Parecer Societário',
    clientFieldLabel: 'Cliente / Requerente *',
    clientPlaceholder: 'Ex: Dr. Roberto Guimarães ou Empresa LTDA',
    locationPlaceholder: 'Ex: Fórum Central - Rio de Janeiro, RJ',
    metricFieldLabel: 'Número do Processo / Foro',
    metricPlaceholder: 'Ex: 0001234-56.2026.8.19.0001',
    showMetricField: true,
    valueFieldLabel: 'Honorários Advocatícios (R$)',
    valuePlaceholder: 'Ex: 12000',
    photosSectionTitle: 'Peças Jurídicas, Minutas & Anexos',
    presetPhotosLabel: '💡 Imagens modelo do ambiente jurídico:',
    presetPhotos: [
      {
        name: 'Escritório & Biblioteca',
        url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Sala de Audiência & Reuniões',
        url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Contratos & Assinaturas',
        url: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=1200&q=80',
      },
    ],
    showBeforeAfter: true,
    beforeAfterTitle: '✨ Andamento Processual (Antes & Depois)',
    beforeLabel: 'Situação Inicial da Lide',
    afterLabel: 'Sentença / Acordo Favorável Concluído',
    conceptFieldLabel: 'Estratégia Jurídica & Tese Aplicada',
    conceptPlaceholder: 'Descreva os fundamentos jurídicos, pedidos liminares, jurisprudência cabível e próximos atos processuais...',
    tagsFieldLabel: 'Ramos & Especialidades',
    tagsPlaceholder: 'Ex: Cível, Tributário, Recurso, Urgente, Contratos',
    defaultTags: ['Jurídico', 'Cível'],
    emptyStateTitle: 'Seu painel jurídico está pronto para novos casos!',
    emptyStateDescription: 'Cadastre seu primeiro processo judicial ou consulta preventiva e acompanhe prazos e honorários.',
    emptyStateButtonText: '+ Cadastrar Novo Caso Jurídico',
  },

  arquitetura: {
    modalTitleNew: 'Novo Projeto de Arquitetura & Fotos',
    modalTitleEdit: 'Editar Projeto de Arquitetura',
    modalSubtitle: 'Cadastre o projeto de interiores, especificações e adicione fotos dos ambientes desenvolvidos.',
    submitButtonText: 'Publicar Projeto',
    itemLabel: 'Projeto de Arquitetura',
    itemLabelPlural: 'Projetos de Arquitetura',
    titleFieldLabel: 'Nome do Projeto *',
    titlePlaceholder: 'Ex: Apartamento Icaraí - Living & Gourmet',
    clientFieldLabel: 'Cliente *',
    clientPlaceholder: 'Ex: Mariana & Rodrigo Silveira',
    locationPlaceholder: 'Ex: Rio Bonito, RJ',
    metricFieldLabel: 'Área (m²)',
    metricPlaceholder: 'Ex: 120',
    showMetricField: true,
    valueFieldLabel: 'Honorários (R$)',
    valuePlaceholder: 'Ex: 14500',
    photosSectionTitle: 'Fotos do Projeto & Galeria',
    presetPhotosLabel: '💡 Fotos modelo de arquitetura para inspiração rápida:',
    presetPhotos: [
      {
        name: 'Living Integrado & Madeira',
        url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Cozinha Gourmet Contemporânea',
        url: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Interiores Tons Terrosos & Boiserie',
        url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Suíte Master com Iluminação Cênica',
        url: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Sala de Estar Minimalista Aconchegante',
        url: 'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Consultório / Recepção Sofisticada',
        url: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=1200&q=80',
      },
    ],
    showBeforeAfter: true,
    beforeAfterTitle: '✨ Antes e Depois (Transformação da Reforma - Opcional)',
    beforeLabel: 'Foto do ANTES (Estado Original)',
    afterLabel: 'Foto do DEPOIS (Projeto Finalizado)',
    conceptFieldLabel: 'Conceito & Detalhes do Projeto',
    conceptPlaceholder: 'Descreva os materiais, paleta de cores (tons terrosos, madeira freijó, iluminação quente 2700K), marcenaria...',
    tagsFieldLabel: 'Tags & Materiais',
    tagsPlaceholder: 'Ex: Madeira Freijó, Iluminação Cênica, Boiserie',
    defaultTags: ['Interiores', 'Rio Bonito'],
    emptyStateTitle: 'Seu escritório está limpo e pronto para novos projetos!',
    emptyStateDescription: 'Cadastre seu primeiro projeto, envie fotos dos ambientes e acompanhe os honorários.',
    emptyStateButtonText: '+ Cadastrar Novo Projeto',
  },

  engenharia: {
    modalTitleNew: 'Nova Obra ou Projeto de Engenharia',
    modalTitleEdit: 'Editar Obra ou Projeto',
    modalSubtitle: 'Cadastre laudos técnicos, projetos estruturais, elétricos, hidráulicos e medições de canteiro.',
    submitButtonText: 'Cadastrar Obra / Projeto',
    itemLabel: 'Obra / Projeto',
    itemLabelPlural: 'Obras & Projetos',
    titleFieldLabel: 'Nome da Obra ou Projeto Estrutural *',
    titlePlaceholder: 'Ex: Edifício Horizon - Estrutural & Fundações',
    clientFieldLabel: 'Construtora / Proprietário *',
    clientPlaceholder: 'Ex: Construtora Alfa & Engenharia S.A.',
    locationPlaceholder: 'Ex: Rio Bonito, RJ',
    metricFieldLabel: 'Área Construída (m²)',
    metricPlaceholder: 'Ex: 450',
    showMetricField: true,
    valueFieldLabel: 'Honorários Técnicos / Contrato (R$)',
    valuePlaceholder: 'Ex: 28000',
    photosSectionTitle: 'Fotos da Obra, Plantas & Canteiro',
    presetPhotosLabel: '💡 Imagens modelo de engenharia e obras:',
    presetPhotos: [
      {
        name: 'Canteiro & Estrutura',
        url: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Projetos & Prancheta Técnica',
        url: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Medição & Vistoria',
        url: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=1200&q=80',
      },
    ],
    showBeforeAfter: true,
    beforeAfterTitle: '✨ Evolução da Obra (Início vs Conclusão)',
    beforeLabel: 'Terreno / Canteiro Inicial',
    afterLabel: 'Obra Concluída & Vistoriada',
    conceptFieldLabel: 'Memorial de Cálculo & Especificações Técnicas',
    conceptPlaceholder: 'Descreva os parâmetros de cálculo, resistência do concreto fck, normas técnicas e memorial descritivo...',
    tagsFieldLabel: 'Disciplinas & Tags Técnicas',
    tagsPlaceholder: 'Ex: Estrutural, Fundação, Elétrico, Laudo, Alvenaria',
    defaultTags: ['Estrutural', 'Construção'],
    emptyStateTitle: 'Seu painel de engenharia está pronto para obras!',
    emptyStateDescription: 'Cadastre seus projetos técnicos, laudos periciais e acompanhe etapas de canteiro.',
    emptyStateButtonText: '+ Cadastrar Nova Obra / Projeto',
  },

  design: {
    modalTitleNew: 'Novo Projeto de Design, Branding ou UI/UX',
    modalTitleEdit: 'Editar Projeto de Design',
    modalSubtitle: 'Cadastre identidades visuais, interfaces digitais, peças gráficas e apresente seus mockups.',
    submitButtonText: 'Publicar Projeto de Design',
    itemLabel: 'Projeto de Design',
    itemLabelPlural: 'Projetos de Design',
    titleFieldLabel: 'Nome do Projeto ou Marca *',
    titlePlaceholder: 'Ex: Rebranding & Identidade Visual Lumina',
    clientFieldLabel: 'Empresa / Cliente *',
    clientPlaceholder: 'Ex: Lumina Skincare Brasil',
    locationPlaceholder: 'Ex: Remoto / Rio de Janeiro, RJ',
    metricFieldLabel: 'Entregáveis / Peças',
    metricPlaceholder: 'Ex: Manual de Marca + 15 Peças',
    showMetricField: true,
    valueFieldLabel: 'Valor do Projeto (R$)',
    valuePlaceholder: 'Ex: 6500',
    photosSectionTitle: 'Mockups & Telas do Projeto',
    presetPhotosLabel: '💡 Imagens modelo de design e branding:',
    presetPhotos: [
      {
        name: 'Manual de Marca & Papelaria',
        url: 'https://images.unsplash.com/photo-1600132806370-bf17e65e942f?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'UI/UX & Design Digital',
        url: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Embalagens & Tipografia',
        url: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?auto=format&fit=crop&w=1200&q=80',
      },
    ],
    showBeforeAfter: true,
    beforeAfterTitle: '✨ Redesign / Antes e Depois da Marca',
    beforeLabel: 'Identidade Antiga (Antes)',
    afterLabel: 'Novo Design & Rebranding (Depois)',
    conceptFieldLabel: 'Conceito Criativo, Tipografia & Paleta',
    conceptPlaceholder: 'Descreva a estratégia da marca, arquétipo, fontes utilizadas, paleta cromática e diretrizes de aplicação...',
    tagsFieldLabel: 'Estilo & Entregáveis',
    tagsPlaceholder: 'Ex: Branding, UI/UX, Logotipo, Minimalista, Editorial',
    defaultTags: ['Branding', 'Identidade Visual'],
    emptyStateTitle: 'Seu estúdio de design está pronto para novas criações!',
    emptyStateDescription: 'Cadastre projetos de branding, interfaces e layouts visuais com mockups elegantes.',
    emptyStateButtonText: '+ Cadastrar Novo Projeto de Design',
  },

  criador_conteudo: {
    modalTitleNew: 'Nova Campanha, Publi ou Conteúdo',
    modalTitleEdit: 'Editar Campanha ou Conteúdo',
    modalSubtitle: 'Cadastre parcerias comerciais, publis gravadas, cronograma de postagens e cachês negociados.',
    submitButtonText: 'Cadastrar Campanha / Publi',
    itemLabel: 'Campanha / Publi',
    itemLabelPlural: 'Campanhas & Publis',
    titleFieldLabel: 'Título da Campanha / Patrocínio *',
    titlePlaceholder: 'Ex: Campanha Primavera - 1 Reels + 4 Stories',
    clientFieldLabel: 'Marca Parceira / Agência *',
    clientPlaceholder: 'Ex: Samsung Brasil / Agência WPP',
    locationPlaceholder: 'Ex: Instagram / TikTok / YouTube',
    metricFieldLabel: 'Alcance / Entregas',
    metricPlaceholder: 'Ex: 250k views esperadas',
    showMetricField: true,
    valueFieldLabel: 'Cachê / Valor Contratado (R$)',
    valuePlaceholder: 'Ex: 12000',
    photosSectionTitle: 'Prints, Fotos da Ação & Mídia Kit',
    presetPhotosLabel: '💡 Imagens modelo de criação de conteúdo:',
    presetPhotos: [
      {
        name: 'Gravação & Setup Criativo',
        url: 'https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Produção de Vídeo & Iluminação',
        url: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Parceria com Marcas',
        url: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=1200&q=80',
      },
    ],
    showBeforeAfter: true,
    beforeAfterTitle: '✨ Métricas de Engajamento (Antes vs Depois)',
    beforeLabel: 'Alcance Médio Anterior',
    afterLabel: 'Resultado Viralizado / Pós-Ação',
    conceptFieldLabel: 'Briefing, Roteiro & Regras da Marca',
    conceptPlaceholder: 'Descreva os entregáveis, hashtags obrigatórias, cupom de desconto, tom de voz e cronograma de publicação...',
    tagsFieldLabel: 'Formatos & Categorias',
    tagsPlaceholder: 'Ex: Reels, TikTok, Publi, Lifestyle, Tecnologia',
    defaultTags: ['Publi', 'Reels', 'Patrocínio'],
    emptyStateTitle: 'Seu painel de criador está pronto para novas parcerias!',
    emptyStateDescription: 'Cadastre suas publis e campanhas patrocinadas, organize prazos e controle cachês.',
    emptyStateButtonText: '+ Cadastrar Nova Campanha / Publi',
  },

  arte_decoracao: {
    modalTitleNew: 'Novo Quadro Decorativo ou Obra de Arte',
    modalTitleEdit: 'Editar Obra ou Quadro',
    modalSubtitle: 'Cadastre telas canvas, fine art, composições de parede e molduras sob medida.',
    submitButtonText: 'Publicar Quadro / Obra',
    itemLabel: 'Quadro / Obra',
    itemLabelPlural: 'Quadros & Obras',
    titleFieldLabel: 'Título da Obra ou Quadro *',
    titlePlaceholder: 'Ex: Tela Canvas Abstrata Ouro & Grafite 120x80cm',
    clientFieldLabel: 'Cliente / Colecionador *',
    clientPlaceholder: 'Ex: Mariana & Rodrigo Silveira',
    locationPlaceholder: 'Ex: Rio Bonito, RJ ou Ateliê',
    metricFieldLabel: 'Dimensões (LxA cm)',
    metricPlaceholder: 'Ex: 120x80 cm',
    showMetricField: true,
    valueFieldLabel: 'Valor da Obra / Quadro (R$)',
    valuePlaceholder: 'Ex: 1850',
    photosSectionTitle: 'Fotos da Obra & Ambientação na Parede',
    presetPhotosLabel: '💡 Inspirações de quadros e composições decorativas:',
    presetPhotos: [
      {
        name: 'Composição Living Contemporâneo',
        url: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Quadro Abstrato Tons Terrosos',
        url: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Moldura Filete Madeira Nobre',
        url: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Galeria de Parede Sofisticada',
        url: 'https://images.unsplash.com/photo-1582561424760-0321d75e81fa?auto=format&fit=crop&w=1200&q=80',
      },
    ],
    showBeforeAfter: true,
    beforeAfterTitle: '✨ Ambientação na Parede (Antes e Depois)',
    beforeLabel: 'Foto da Parede Vazia (Antes)',
    afterLabel: 'Foto com o Quadro Instalado (Depois)',
    conceptFieldLabel: 'Técnica, Moldura & Conceito Artístico',
    conceptPlaceholder: 'Descreva a técnica de impressão (Fine Art em algodão 310g, canvas, vidro museu), acabamento da moldura...',
    tagsFieldLabel: 'Estilo & Materiais',
    tagsPlaceholder: 'Ex: Canvas, Moldura Freijó, Fine Art, Abstrato',
    defaultTags: ['Canvas', 'Fine Art', 'Decoração'],
    emptyStateTitle: 'Sua galeria de quadros está pronta para novas obras!',
    emptyStateDescription: 'Cadastre suas peças decorativas, fotos de composições em paredes reais e organize pedidos.',
    emptyStateButtonText: '+ Cadastrar Novo Quadro / Obra',
  },

  consultoria: {
    modalTitleNew: 'Novo Projeto de Consultoria ou Mentoria',
    modalTitleEdit: 'Editar Projeto de Consultoria',
    modalSubtitle: 'Cadastre diagnósticos empresariais, planos de ação, reuniões estratégicas e honorários contratados.',
    submitButtonText: 'Cadastrar Projeto de Consultoria',
    itemLabel: 'Projeto de Consultoria',
    itemLabelPlural: 'Projetos de Consultoria',
    titleFieldLabel: 'Nome do Projeto de Consultoria *',
    titlePlaceholder: 'Ex: Reestruturação Financeira & Otimização de Processos',
    clientFieldLabel: 'Empresa Cliente / Contratante *',
    clientPlaceholder: 'Ex: Grupo Comercial Vanguarda LTDA',
    locationPlaceholder: 'Ex: Presencial / Remoto ou Rio de Janeiro, RJ',
    metricFieldLabel: 'Duração / Horas de Mentoria',
    metricPlaceholder: 'Ex: 6 meses (48h)',
    showMetricField: true,
    valueFieldLabel: 'Honorários de Consultoria (R$)',
    valuePlaceholder: 'Ex: 18000',
    photosSectionTitle: 'Apresentações, Relatórios & Métricas',
    presetPhotosLabel: '💡 Imagens modelo corporativas e de gestão:',
    presetPhotos: [
      {
        name: 'Reunião Estratégica & Diagnóstico',
        url: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Dashboard & Análise de Métricas',
        url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Planejamento no Quadro',
        url: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=1200&q=80',
      },
    ],
    showBeforeAfter: true,
    beforeAfterTitle: '✨ Resultados / Diagnóstico Antes vs Depois',
    beforeLabel: 'Diagnóstico Inicial (Gargalos e Custos)',
    afterLabel: 'Pós-Implementação (Eficiência e Lucro)',
    conceptFieldLabel: 'Escopo de Atuação & Metodologia',
    conceptPlaceholder: 'Descreva os pilares trabalhados, ferramentas de gestão, cronograma de reuniões e metas de KPIs...',
    tagsFieldLabel: 'Áreas & Metodologias',
    tagsPlaceholder: 'Ex: Gestão Financeira, OKRs, Processos, Expansão',
    defaultTags: ['Consultoria', 'Estratégia'],
    emptyStateTitle: 'Seu painel de consultoria está pronto para novos clientes!',
    emptyStateDescription: 'Cadastre seus projetos corporativos, defina metas de entregas e acompanhe honorários.',
    emptyStateButtonText: '+ Cadastrar Novo Projeto de Consultoria',
  },

  saude_estetica: {
    modalTitleNew: 'Novo Protocolo ou Atendimento Clínico',
    modalTitleEdit: 'Editar Protocolo ou Atendimento',
    modalSubtitle: 'Cadastre planos de tratamento, pacotes de procedimentos, sessões e evolução de pacientes.',
    submitButtonText: 'Cadastrar Atendimento / Pacote',
    itemLabel: 'Atendimento / Protocolo',
    itemLabelPlural: 'Protocolos & Atendimentos',
    titleFieldLabel: 'Nome do Protocolo ou Procedimento *',
    titlePlaceholder: 'Ex: Protocolo Rejuvenescimento Facial Completo',
    clientFieldLabel: 'Paciente / Cliente *',
    clientPlaceholder: 'Ex: Juliana Mendes',
    locationPlaceholder: 'Ex: Consultório Principal - Rio Bonito, RJ',
    metricFieldLabel: 'Sessões / Duração',
    metricPlaceholder: 'Ex: 6 sessões',
    showMetricField: true,
    valueFieldLabel: 'Valor do Protocolo / Sessões (R$)',
    valuePlaceholder: 'Ex: 4500',
    photosSectionTitle: 'Fotos Clínicas & Acompanhamento de Evolução',
    presetPhotosLabel: '💡 Imagens modelo de estética e atendimento clínico:',
    presetPhotos: [
      {
        name: 'Consultório & Atendimento',
        url: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Procedimentos & Cuidado',
        url: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Tecnologia & Equipamentos',
        url: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=1200&q=80',
      },
    ],
    showBeforeAfter: true,
    beforeAfterTitle: '✨ Evolução do Paciente (Antes e Depois)',
    beforeLabel: 'Avaliação Inicial (Antes)',
    afterLabel: 'Resultado Final do Protocolo (Depois)',
    conceptFieldLabel: 'Prescrição, Produtos & Orientações',
    conceptPlaceholder: 'Descreva os princípios ativos utilizados, frequência das sessões, cuidados home-care e retornos...',
    tagsFieldLabel: 'Procedimentos & Especialidades',
    tagsPlaceholder: 'Ex: Estética Facial, Laser, Harmonização, Nutrição',
    defaultTags: ['Estética', 'Tratamento'],
    emptyStateTitle: 'Seu consultório está pronto para novos atendimentos!',
    emptyStateDescription: 'Cadastre pacientes, acompanhe pacotes de sessões e controle o faturamento clínico.',
    emptyStateButtonText: '+ Cadastrar Novo Atendimento',
  },

  imobiliario: {
    modalTitleNew: 'Novo Imóvel no Catálogo ou Captação',
    modalTitleEdit: 'Editar Imóvel',
    modalSubtitle: 'Cadastre imóveis para venda ou locação, características, fotos dos ambientes e acompanhe propostas.',
    submitButtonText: 'Publicar Imóvel no Catálogo',
    itemLabel: 'Imóvel / Captação',
    itemLabelPlural: 'Imóveis & Captações',
    titleFieldLabel: 'Título do Imóvel / Anúncio *',
    titlePlaceholder: 'Ex: Cobertura Duplex Vista Mar - 4 Suítes',
    clientFieldLabel: 'Proprietário(a) / Vendedor *',
    clientPlaceholder: 'Ex: Carlos Alberto Miranda',
    locationPlaceholder: 'Ex: Bairro Nobre - Rio Bonito, RJ',
    metricFieldLabel: 'Área Útil (m²)',
    metricPlaceholder: 'Ex: 220',
    showMetricField: true,
    valueFieldLabel: 'Valor do Imóvel / Aluguel (R$)',
    valuePlaceholder: 'Ex: 1250000',
    photosSectionTitle: 'Fotos do Imóvel & Ambientes',
    presetPhotosLabel: '💡 Imagens modelo de imóveis residenciais:',
    presetPhotos: [
      {
        name: 'Living & Varanda',
        url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Fachada & Condomínio',
        url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Cozinha Gourmet',
        url: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80',
      },
    ],
    showBeforeAfter: true,
    beforeAfterTitle: '✨ Home Staging ou Reforma (Antes e Depois)',
    beforeLabel: 'Imóvel Original / Desocupado',
    afterLabel: 'Imóvel Decorado / Pronto para Morar',
    conceptFieldLabel: 'Descrição do Imóvel & Comodidades',
    conceptPlaceholder: 'Descreva quartos, suítes, vagas, condomínio, IPTU, comodidades de lazer e diferenciais de localização...',
    tagsFieldLabel: 'Características & Tags',
    tagsPlaceholder: 'Ex: Vista Mar, 4 Suítes, Alto Padrão, Varanda Gourmet',
    defaultTags: ['Venda', 'Alto Padrão'],
    emptyStateTitle: 'Sua carteira de imóveis está pronta para novas captações!',
    emptyStateDescription: 'Cadastre imóveis exclusivos, adicione fotos de alta resolução e acompanhe propostas.',
    emptyStateButtonText: '+ Cadastrar Novo Imóvel',
  },

  fotografia: {
    modalTitleNew: 'Novo Ensaio Fotográfico ou Cobertura',
    modalTitleEdit: 'Editar Ensaio Fotográfico',
    modalSubtitle: 'Cadastre sessões de fotos, casamentos, eventos comerciais e entregas de galerias aos clientes.',
    submitButtonText: 'Publicar Ensaio na Galeria',
    itemLabel: 'Ensaio Fotográfico',
    itemLabelPlural: 'Ensaios Fotográficos',
    titleFieldLabel: 'Nome do Ensaio ou Evento *',
    titlePlaceholder: 'Ex: Ensaio Gestante Externa / Casamento Marina & Pedro',
    clientFieldLabel: 'Cliente / Contratante *',
    clientPlaceholder: 'Ex: Marina & Pedro Albuquerque',
    locationPlaceholder: 'Ex: Praia Vermelha ou Rio Bonito, RJ',
    metricFieldLabel: 'Qtd. Fotos Entregues / Horas',
    metricPlaceholder: 'Ex: 80 fotos tratadas',
    showMetricField: true,
    valueFieldLabel: 'Valor do Pacote Fotográfico (R$)',
    valuePlaceholder: 'Ex: 3800',
    photosSectionTitle: 'Melhores Fotos do Ensaio (Galeria)',
    presetPhotosLabel: '💡 Imagens modelo de ensaios fotográficos:',
    presetPhotos: [
      {
        name: 'Retrato & Iluminação de Estúdio',
        url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Casamento & Emoção',
        url: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Fotografia Externa & Natureza',
        url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
      },
    ],
    showBeforeAfter: true,
    beforeAfterTitle: '✨ Tratamento de Cor & Retoque (RAW vs Editada)',
    beforeLabel: 'Foto RAW Original (Sem Tratamento)',
    afterLabel: 'Foto com Color Grading Finalizado',
    conceptFieldLabel: 'Direção Visual, Locação & Equipamento',
    conceptPlaceholder: 'Descreva a direção estética, paleta de cores (quente/fria), lentes usadas e roteiro do ensaio...',
    tagsFieldLabel: 'Gênero & Estilo Fotográfico',
    tagsPlaceholder: 'Ex: Retrato, Casamento, Golden Hour, Externa, PB',
    defaultTags: ['Ensaio', 'Externa'],
    emptyStateTitle: 'Sua galeria fotográfica está pronta para novos ensaios!',
    emptyStateDescription: 'Cadastre suas sessões de fotos, envie imagens em alta resolução e encante seus clientes.',
    emptyStateButtonText: '+ Cadastrar Novo Ensaio Fotográfico',
  },

  tecnologia: {
    modalTitleNew: 'Novo Projeto de Software, App ou API',
    modalTitleEdit: 'Editar Projeto de Software',
    modalSubtitle: 'Cadastre especificações de sistemas, sprints de desenvolvimento, entregas técnicas e contratos.',
    submitButtonText: 'Cadastrar Projeto de Software',
    itemLabel: 'Projeto de Software',
    itemLabelPlural: 'Projetos de Software',
    titleFieldLabel: 'Nome do Software ou Aplicação *',
    titlePlaceholder: 'Ex: Plataforma Web SaaS de Gestão Financeira',
    clientFieldLabel: 'Cliente / Startup Contratante *',
    clientPlaceholder: 'Ex: InovaTech Soluções Digitais LTDA',
    locationPlaceholder: 'Ex: Remoto / Cloud AWS / Rio Bonito, RJ',
    metricFieldLabel: 'Sprints / Prazo Estimado',
    metricPlaceholder: 'Ex: 6 sprints (3 meses)',
    showMetricField: true,
    valueFieldLabel: 'Valor do Contrato de Desenvolvimento (R$)',
    valuePlaceholder: 'Ex: 35000',
    photosSectionTitle: 'Screenshots do Sistema, Arquitetura & Telas',
    presetPhotosLabel: '💡 Imagens modelo de software e telas digitais:',
    presetPhotos: [
      {
        name: 'Dashboard & Interface Digital',
        url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Código & Engenharia de Software',
        url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Cloud Infrastructure & APIs',
        url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80',
      },
    ],
    showBeforeAfter: true,
    beforeAfterTitle: '✨ Refatoração / Nova Versão (Antes e Depois)',
    beforeLabel: 'Sistema Legado / Versão Anterior',
    afterLabel: 'Nova Interface & Arquitetura Moderna',
    conceptFieldLabel: 'Stack Tecnológica & Arquitetura',
    conceptPlaceholder: 'Descreva as tecnologias utilizadas (React, Node.js, PostgreSQL, Docker, AWS), microsserviços e padrões...',
    tagsFieldLabel: 'Stack & Tecnologias',
    tagsPlaceholder: 'Ex: React, Node.js, TypeScript, Cloud, Mobile',
    defaultTags: ['Web App', 'TypeScript', 'Cloud'],
    emptyStateTitle: 'Seu painel de desenvolvimento está pronto para projetos!',
    emptyStateDescription: 'Cadastre suas aplicações, controle sprints de entrega e organize honorários de software.',
    emptyStateButtonText: '+ Cadastrar Novo Projeto de Software',
  },

  marketing: {
    modalTitleNew: 'Nova Campanha de Marketing ou Tráfego',
    modalTitleEdit: 'Editar Campanha de Marketing',
    modalSubtitle: 'Cadastre campanhas de anúncios, gestão de redes sociais, metas de conversão e relatórios de ROI.',
    submitButtonText: 'Cadastrar Campanha de Marketing',
    itemLabel: 'Campanha de Marketing',
    itemLabelPlural: 'Campanhas de Marketing',
    titleFieldLabel: 'Nome da Campanha ou Conta de Anúncios *',
    titlePlaceholder: 'Ex: Aquisição & Tráfego Direto - Lançamento',
    clientFieldLabel: 'Empresa / Infoprodutor *',
    clientPlaceholder: 'Ex: Dr. Fernando Alves Cursos Online',
    locationPlaceholder: 'Ex: Meta Ads & Google Ads / Remoto',
    metricFieldLabel: 'Investimento em Tráfego (R$)',
    metricPlaceholder: 'Ex: 10000',
    showMetricField: true,
    valueFieldLabel: 'Honorários de Gestão (R$)',
    valuePlaceholder: 'Ex: 5000',
    photosSectionTitle: 'Criativos da Campanha & Prints de Métricas',
    presetPhotosLabel: '💡 Imagens modelo de marketing e conversão:',
    presetPhotos: [
      {
        name: 'Dashboard de Vendas & ROI',
        url: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Criativos & Peças Gráficas',
        url: 'https://images.unsplash.com/photo-1542744094-3a3172720a4a?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Estratégia de Aquisição',
        url: 'https://images.unsplash.com/photo-1533750516457-a7f992034fec?auto=format&fit=crop&w=1200&q=80',
      },
    ],
    showBeforeAfter: true,
    beforeAfterTitle: '✨ Otimização de Resultados (Antes vs Depois)',
    beforeLabel: 'Métricas Iniciais (CPA Alto / Poucas Vendas)',
    afterLabel: 'Campanha Otimizada (ROAS Positivo e Escala)',
    conceptFieldLabel: 'Estratégia do Funil, Copy & Segmentação',
    conceptPlaceholder: 'Descreva os públicos testados, criativos vencedores, ângulo de copy, canais de aquisição e metas de CPA...',
    tagsFieldLabel: 'Canais & Estratégias',
    tagsPlaceholder: 'Ex: Meta Ads, Google Ads, Tráfego Pago, Lançamento',
    defaultTags: ['Tráfego Pago', 'Meta Ads'],
    emptyStateTitle: 'Seu painel de marketing está pronto para campanhas!',
    emptyStateDescription: 'Cadastre clientes de tráfego pago e redes sociais, acompanhe metas de ROI e honorários.',
    emptyStateButtonText: '+ Cadastrar Nova Campanha',
  },

  eventos: {
    modalTitleNew: 'Novo Evento, Casamento ou Celebração',
    modalTitleEdit: 'Editar Evento',
    modalSubtitle: 'Cadastre casamentos, festas corporativas, cronogramas de cerimonial, fornecedores e fotos.',
    submitButtonText: 'Publicar Evento no Portfólio',
    itemLabel: 'Evento / Celebração',
    itemLabelPlural: 'Eventos & Celebrações',
    titleFieldLabel: 'Nome do Evento ou Noivos *',
    titlePlaceholder: 'Ex: Casamento Luiza & Gabriel - Fazenda Imperial',
    clientFieldLabel: 'Noivos ou Contratante do Evento *',
    clientPlaceholder: 'Ex: Luiza Albuquerque & Gabriel Ramos',
    locationPlaceholder: 'Ex: Fazenda Solar - Rio Bonito, RJ',
    metricFieldLabel: 'Qtd. Convidados',
    metricPlaceholder: 'Ex: 250 convidados',
    showMetricField: true,
    valueFieldLabel: 'Honorários de Assessoria / Produção (R$)',
    valuePlaceholder: 'Ex: 9500',
    photosSectionTitle: 'Fotos da Decoração, Espaço & Cerimônia',
    presetPhotosLabel: '💡 Imagens modelo de eventos e casamentos:',
    presetPhotos: [
      {
        name: 'Mesa de Bolo & Flores Nobres',
        url: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Iluminação Cênica & Salão',
        url: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Cerimônia ao Ar Livre',
        url: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&w=1200&q=80',
      },
    ],
    showBeforeAfter: true,
    beforeAfterTitle: '✨ Montagem do Evento (Salão Vazio vs Montado)',
    beforeLabel: 'Espaço Antes da Montagem',
    afterLabel: 'Decoração Completa & Evento Realizado',
    conceptFieldLabel: 'Roteiro, Fornecedores & Estilo do Evento',
    conceptPlaceholder: 'Descreva o cronograma do dia, fornecedores envolvidos (buffet, DJ, iluminação, floral) e protocolo...',
    tagsFieldLabel: 'Estilo & Tipo de Evento',
    tagsPlaceholder: 'Ex: Casamento, Ao Ar Livre, Rústico Chic, 15 Anos',
    defaultTags: ['Casamento', 'Assessoria'],
    emptyStateTitle: 'Sua agenda de eventos está pronta para novos cadastros!',
    emptyStateDescription: 'Cadastre seus próximos eventos, organize datas de fornecedores e exiba fotos do portfólio.',
    emptyStateButtonText: '+ Cadastrar Novo Evento',
  },

  autonomo: {
    modalTitleNew: 'Novo Serviço ou Atendimento',
    modalTitleEdit: 'Editar Serviço ou Atendimento',
    modalSubtitle: 'Cadastre atendimentos especializados, ordens de serviço, entregas e honorários contratados.',
    submitButtonText: 'Cadastrar Serviço',
    itemLabel: 'Serviço / Atendimento',
    itemLabelPlural: 'Serviços & Atendimentos',
    titleFieldLabel: 'Nome do Serviço ou Atendimento *',
    titlePlaceholder: 'Ex: Atendimento Especializado & Execução',
    clientFieldLabel: 'Cliente Contratante *',
    clientPlaceholder: 'Ex: Mariana & Rodrigo Silveira',
    locationPlaceholder: 'Ex: Rio Bonito, RJ ou Remoto',
    metricFieldLabel: 'Prazo / Detalhes Adicionais',
    metricPlaceholder: 'Ex: 15 dias',
    showMetricField: true,
    valueFieldLabel: 'Valor do Serviço (R$)',
    valuePlaceholder: 'Ex: 3500',
    photosSectionTitle: 'Fotos & Registros do Atendimento',
    presetPhotosLabel: '💡 Imagens modelo de atendimentos e serviços:',
    presetPhotos: [
      {
        name: 'Ambiente Profissional',
        url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Trabalho em Execução',
        url: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=1200&q=80',
      },
    ],
    showBeforeAfter: true,
    beforeAfterTitle: '✨ Resultados / Antes e Depois',
    beforeLabel: 'Situação Inicial',
    afterLabel: 'Serviço Concluído com Sucesso',
    conceptFieldLabel: 'Detalhamento & Escopo do Serviço',
    conceptPlaceholder: 'Descreva as etapas do atendimento, garantias, entregáveis e orientações ao cliente...',
    tagsFieldLabel: 'Tags & Categorias',
    tagsPlaceholder: 'Ex: Atendimento, Presencial, Personalizado, Urgente',
    defaultTags: ['Serviço', 'Profissional'],
    emptyStateTitle: 'Seu painel está limpo e pronto para novos serviços!',
    emptyStateDescription: 'Cadastre seus atendimentos, organize prazos e controle o faturamento do seu negócio.',
    emptyStateButtonText: '+ Cadastrar Novo Serviço',
  },

  outro: {
    modalTitleNew: 'Novo Projeto ou Atendimento',
    modalTitleEdit: 'Editar Projeto ou Atendimento',
    modalSubtitle: 'Cadastre suas entregas, contratos, produtos ou serviços e acompanhe clientes e honorários.',
    submitButtonText: 'Cadastrar Item',
    itemLabel: 'Projeto / Serviço',
    itemLabelPlural: 'Projetos & Atividades',
    titleFieldLabel: 'Título do Projeto ou Atendimento *',
    titlePlaceholder: 'Ex: Contrato de Prestação de Serviços',
    clientFieldLabel: 'Cliente / Contratante *',
    clientPlaceholder: 'Ex: Mariana & Rodrigo Silveira',
    locationPlaceholder: 'Ex: Rio Bonito, RJ ou Online',
    metricFieldLabel: 'Prazo ou Quantidade',
    metricPlaceholder: 'Ex: 30 dias',
    showMetricField: true,
    valueFieldLabel: 'Valor / Honorários (R$)',
    valuePlaceholder: 'Ex: 4500',
    photosSectionTitle: 'Fotos & Anexos Visuais',
    presetPhotosLabel: '💡 Imagens modelo para inspiração:',
    presetPhotos: [
      {
        name: 'Ambiente Profissional',
        url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
      },
      {
        name: 'Trabalho em Execução',
        url: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=1200&q=80',
      },
    ],
    showBeforeAfter: true,
    beforeAfterTitle: '✨ Resultados / Antes e Depois',
    beforeLabel: 'Situação Inicial',
    afterLabel: 'Conclusão e Entrega Realizada',
    conceptFieldLabel: 'Descrição & Detalhes do Escopo',
    conceptPlaceholder: 'Descreva os entregáveis, prazos, observações importantes e termos acertados com o cliente...',
    tagsFieldLabel: 'Tags & Especificações',
    tagsPlaceholder: 'Ex: Prioritário, Contrato, Entregue, Atendimento',
    defaultTags: ['Profissional', 'Gestão'],
    emptyStateTitle: 'Seu painel está limpo e pronto para novos cadastros!',
    emptyStateDescription: 'Cadastre seus projetos, contratos ou atendimentos e acompanhe clientes e honorários.',
    emptyStateButtonText: '+ Cadastrar Novo Item',
  },
};
